# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Record')),
                ('name', models.CharField(max_length=100)),
                ('synopsis', models.TextField(blank=True, max_length=250, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('base.record',),
        ),
    ]
