# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
