# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('term_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Term')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.term',),
        ),
    ]
