version: '3'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8000:80"
      - "4430:443"
    depends_on:
      - api

  api:
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app:ro
    ports:
      - "8000"
    environment:
      - SETTINGS_MODE
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_SERVER
      - MONGO_PORT
      - MONGO_DBNAME
    command: /usr/local/bin/gunicorn -c /usr/src/app/gunicorn.py -w 1 -b :8000 wsgi
