from django.contrib import admin
from cms.models import (
    Audience, Name, Abstract, Announcement, Article, Description,
    Identifier, Language, License, Link, Log, Page, Record, RecordSet,
    Relation, Subject, Term, Unit, Vocabulary)
from tour.models import (
    Place, Space, State, City, Neighborhood, District, Zipcode)
from aggregator.models import (
    Source, Service, Rights)
from archive.models import (
    File, Image, Document, Video, ArchiveEvent, Aspect)
from timeline.models import (
    Period, Event, Exhibit, Performance)
from catalog.models import (
    Work, Ephemeron, Dimension, Medium, Genre, Condition)
from crosswalk.models import (
    Schema)
from directory.models import (
    Entity, Person, Organization, School, Gallery, Museum, Venue, ContactItem,
    Account, Address, Email, Phone, Website, Hours)

admin.site.register(Abstract)
admin.site.register(Account)
admin.site.register(Address)
admin.site.register(Announcement)
admin.site.register(ArchiveEvent)
admin.site.register(Article)
admin.site.register(Aspect)
admin.site.register(Audience)
admin.site.register(City)
admin.site.register(Condition)
admin.site.register(ContactItem)
admin.site.register(Description)
admin.site.register(Dimension)
admin.site.register(District)
admin.site.register(Document)
admin.site.register(Email)
admin.site.register(Entity)
admin.site.register(Ephemeron)
admin.site.register(Event)
admin.site.register(Exhibit)
admin.site.register(File)
admin.site.register(Gallery)
admin.site.register(Genre)
admin.site.register(Hours)
admin.site.register(Identifier)
admin.site.register(Image)
admin.site.register(Language)
admin.site.register(License)
admin.site.register(Link)
admin.site.register(Log)
admin.site.register(Medium)
admin.site.register(Museum)
admin.site.register(Name)
admin.site.register(Neighborhood)
admin.site.register(Organization)
admin.site.register(Page)
admin.site.register(Performance)
admin.site.register(Period)
admin.site.register(Person)
admin.site.register(Phone)
admin.site.register(Place)
admin.site.register(Record)
admin.site.register(RecordSet)
admin.site.register(Relation)
admin.site.register(Rights)
admin.site.register(Schema)
admin.site.register(School)
admin.site.register(Service)
admin.site.register(Source)
admin.site.register(Space)
admin.site.register(State)
admin.site.register(Subject)
admin.site.register(Term)
admin.site.register(Unit)
admin.site.register(Venue)
admin.site.register(Video)
admin.site.register(Vocabulary)
admin.site.register(Website)
admin.site.register(Work)
admin.site.register(Zipcode)