# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_work_related_contacts'),
        ('placefinder', '0001_initial'),
        ('directory', '0001_initial'),
        ('cms', '0002_page_related_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('event_type', models.CharField(choices=[('EXHIBITION', 'exhibition'), ('PERFORMANCE', 'performance')], default='EXHIBITION', max_length=20)),
                ('related_contacts', models.ManyToManyField(blank=True, to='directory.Contact')),
                ('related_events', models.ManyToManyField(blank=True, to='timeline.Event')),
                ('related_pages', models.ManyToManyField(blank=True, to='cms.Page')),
                ('related_venues', models.ManyToManyField(blank=True, to='placefinder.Venue')),
                ('related_works', models.ManyToManyField(blank=True, to='catalog.Work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
