# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Record')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.record',),
        ),
    ]
