# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('EXHIBITION', 'exhibition'), ('PERFORMANCE', 'performance')], default='EXHIBITION', max_length=20),
        ),
    ]
