# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('aspect', models.CharField(choices=[('main', 'Main'), ('recto', 'Recto'), ('verso', 'Verso'), ('detail', 'detail'), ('signature', 'signature')], default='main', max_length=25)),
                ('checksum', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(choices=[('event', 'event'), ('work', 'work'), ('person', 'person'), ('organization', 'organization'), ('page', 'page')], max_length=25)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_web_public', models.BooleanField(default=True)),
                ('images', models.ManyToManyField(blank=True, to='api.Image')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(choices=[('has_contributor', 'has contributor'), ('has_creator', 'has creator'), ('has_curator', 'has curator'), ('has_employee', 'has employee'), ('has_exhibitor', 'has exhibitor'), ('has_friend', 'has friend'), ('has_member', 'has member'), ('has_organizer', 'has organizer'), ('has_owner', 'has owner'), ('has_parent', 'has parent'), ('has_producer', 'has producer'), ('has_publisher', 'has publisher'), ('has_affiliation', 'has affiliation'), ('has_spouse', 'has spouse'), ('has_venue', 'has_venue'), ('located_at', 'located at'), ('started_at', 'started at'), ('ended_at', 'ended at'), ('born_at', 'born at'), ('died_at', 'died at'), ('part_of', 'part of'), ('same_as', 'same as'), ('same_as', 'same as'), ('has_record_source', 'has record source'), ('has_record_parent', 'has record parent'), ('has_record_license', 'has record license')], max_length=25)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('dobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_direct_object', to='api.Record')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_subject', to='api.Record')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('vocabulary', models.CharField(blank=True, choices=[('visualist', 'The Visualist'), ('aat', 'Getty Art and Architecture Thesaurus'), ('ulan', 'Getty Union List of Artist Names'), ('lccn', 'Library of Congress Control Number'), ('viaf', 'Virtual International Authority File')], max_length=25, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Term')),
                ('same_as', models.ManyToManyField(blank=True, related_name='_term_same_as_+', to='api.Term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='related',
            field=models.ManyToManyField(blank=True, through='api.Relation', to='api.Record'),
        ),
        migrations.AddField(
            model_name='record',
            name='terms',
            field=models.ManyToManyField(blank=True, to='api.Term'),
        ),
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Record'),
        ),
    ]
