# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='email',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
