# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
