# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='term',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='term',
            name='same_as',
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Snippet'),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Snippet'),
        ),
    ]
