# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170913_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='license',
        ),
        migrations.AlterField(
            model_name='record',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensed_records', to='api.Resource'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensed_snippets', to='api.Resource'),
        ),
        migrations.DeleteModel(
            name='License',
        ),
    ]
