# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170913_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name_primary',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
