# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170926_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
