# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171001_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='predicate',
            field=models.CharField(choices=[('has_contributor', 'has contributor'), ('has_creator', 'has creator'), ('has_curator', 'has curator'), ('has_editor', 'has editor'), ('has_employee', 'has employee'), ('has_exhibitor', 'has exhibitor'), ('has_friend', 'has friend'), ('has_member', 'has member'), ('has_organizer', 'has organizer'), ('has_owner', 'has owner'), ('has_parent', 'has parent'), ('has_producer', 'has producer'), ('has_publisher', 'has publisher'), ('has_affiliation', 'has affiliation'), ('has_spouse', 'has spouse'), ('has_translator', 'has translator'), ('has_venue', 'has_venue'), ('located_at', 'located at'), ('started_at', 'started at'), ('ended_at', 'ended at'), ('born_at', 'born at'), ('died_at', 'died at'), ('part_of', 'part of'), ('same_as', 'same as'), ('same_as', 'same as'), ('has_record_source', 'has record source'), ('has_record_parent', 'has record parent'), ('has_record_license', 'has record license')], max_length=25),
        ),
    ]
