# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171008_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
