# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_snippet_source_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_url',
            new_name='base_url',
        ),
    ]
