# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 05:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170926_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
