# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 17:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_record_name_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('primary', models.CharField(max_length=250)),
                ('secondary', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='record',
            old_name='is_appointment_only',
            new_name='by_appointment_only',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='records',
            new_name='related',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='record',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name_personal',
        ),
        migrations.RemoveField(
            model_name='record',
            name='name_primary',
        ),
        migrations.RemoveField(
            model_name='record',
            name='originated_on',
        ),
        migrations.RemoveField(
            model_name='record',
            name='terminated_on',
        ),
        migrations.AddField(
            model_name='record',
            name='license',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='records_licensed', to='api.Resource'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='lifespan',
            field=django.contrib.postgres.fields.ranges.DateRangeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='record',
            name='emails',
            field=models.ManyToManyField(blank=True, to='api.Email'),
        ),
        migrations.AlterField(
            model_name='record',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='record',
            name='phones',
            field=models.ManyToManyField(blank=True, to='api.Phone'),
        ),
        migrations.AlterField(
            model_name='record',
            name='published_on',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, to='api.SocialAccount'),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
        migrations.AddField(
            model_name='name',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Record'),
        ),
        migrations.AddField(
            model_name='name',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
