# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record_properties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='source',
        ),
        migrations.RemoveField(
            model_name='email',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='source',
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='term',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='term',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='record',
            name='source',
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Record'),
        ),
        migrations.AlterField(
            model_name='license',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='label',
            field=models.CharField(choices=[('event', 'event'), ('work', 'work'), ('person', 'person'), ('organization', 'organization'), ('page', 'page')], max_length=25),
        ),
        migrations.AlterField(
            model_name='relation',
            name='predicate',
            field=models.CharField(choices=[('has_contributor', 'has contributor'), ('has_creator', 'has creator'), ('has_curator', 'has curator'), ('has_employee', 'has employee'), ('has_exhibitor', 'has exhibitor'), ('has_friend', 'has friend'), ('has_member', 'has member'), ('has_organizer', 'has organizer'), ('has_owner', 'has owner'), ('has_parent', 'has parent'), ('has_producer', 'has producer'), ('has_publisher', 'has publisher'), ('has_affiliation', 'has affiliation'), ('has_spouse', 'has spouse'), ('has_venue', 'has_venue'), ('located_at', 'located at'), ('started_at', 'started at'), ('ended_at', 'ended at'), ('born_at', 'born at'), ('died_at', 'died at'), ('part_of', 'part of'), ('same_as', 'same as'), ('same_as', 'same as'), ('has_record_source', 'has record source'), ('has_record_parent', 'has record parent')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='SocialAccount',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
