# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170908_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='same_as',
            field=models.URLField(blank=True),
        ),
    ]
