# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170913_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='source',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
            preserve_default=False,
        ),
    ]
