# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_term_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='source',
        ),
        migrations.AlterField(
            model_name='term',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Resource'),
        ),
    ]
