# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170928_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='license',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records_licensed', to='api.License'),
        ),
    ]
