# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171002_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
