# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170908_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='creator', to='api.Work'),
        ),
        migrations.AlterField(
            model_name='event',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_to', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curator_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='exhibitors',
            field=models.ManyToManyField(blank=True, related_name='exhibitor_at', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='producer_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='represented_by', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='dissolved',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employed_by', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founded',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='founded_at',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Place'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hours',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_at',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthplace_of', to='api.Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='died',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='died_at',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deathplace_of', to='api.Place'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_person_friends_+', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_first',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationalities',
            field=models.ManyToManyField(blank=True, to='api.Nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_person_parents_+', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='place',
            name='body',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Snippet'),
        ),
        migrations.AlterField(
            model_name='place',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='has_venue', to='api.Event'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Post'),
        ),
        migrations.AlterField(
            model_name='record',
            name='identifiers',
            field=models.ManyToManyField(blank=True, to='api.Identifier'),
        ),
        migrations.AlterField(
            model_name='record',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.Image'),
        ),
        migrations.AlterField(
            model_name='work',
            name='completed',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.ManyToManyField(blank=True, related_name='works_created_here', to='api.Place'),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='works_here', to='api.Place'),
        ),
        migrations.AlterField(
            model_name='work',
            name='published',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='version',
            field=models.TextField(blank=True),
        ),
    ]
