# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170913_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='email',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='record',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensed_records', to='api.Work'),
        ),
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licensed_snippets', to='api.Work'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.AlterField(
            model_name='term',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
