# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170913_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='categories',
        ),
        migrations.AddField(
            model_name='collection',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
        migrations.AddField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(to='api.Category'),
        ),
    ]
