# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171004_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='value',
        ),
        migrations.RemoveField(
            model_name='source',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='source',
            name='date',
        ),
        migrations.RemoveField(
            model_name='source',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='source',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='source',
            name='title',
        ),
        migrations.AddField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='precision_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='source',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
