# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170928_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='dobject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_direct_object', to='api.Record'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_subject', to='api.Record'),
        ),
    ]
