# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170908_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='died',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
