# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171005_0222'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=set([('date', 'precision_days')]),
        ),
    ]
