# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170913_0356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='term',
            name='vocabulary',
        ),
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AddField(
            model_name='category',
            name='vocabulary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='source',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='api.Work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='address_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationalities',
            field=models.ManyToManyField(blank=True, related_name='people_of_nationality', to='api.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('value', 'parent'), ('value', 'vocabulary')]),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
