# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170908_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributor_to', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curator_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='exhibitors',
            field=models.ManyToManyField(blank=True, related_name='exhibitor_at', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='event',
            name='producers',
            field=models.ManyToManyField(blank=True, related_name='producer_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='represented_by', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='employed_by', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='member_of', to='api.Entity'),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_person_friends_+', to='api.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationalities',
            field=models.ManyToManyField(blank=True, to='api.Nationality'),
        ),
        migrations.AlterField(
            model_name='person',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='_person_parents_+', to='api.Person'),
        ),
    ]
