# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 02:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170930_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
