# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171005_0229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='value',
            new_name='extra',
        ),
        migrations.AddField(
            model_name='source',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='date',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='label',
            field=models.CharField(choices=[('book', 'book'), ('website', 'website'), ('journal_article', 'journal article'), ('newspaper_article', 'newspaper article')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='pages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='place',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='publisher',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
