# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170912_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='email',
            name='value',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='checksum',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='value',
            field=models.TextField(choices=[('US', 'United States of America'), ('CA', 'Canada'), ('MX', 'Mexico')], unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.SlugField(unique=True),
        ),
    ]
