# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170913_0407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Term',
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['value']},
        ),
    ]
