# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171005_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
