# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170912_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_locality',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_postal_code',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='email',
            name='value',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='value',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='aspect',
            field=models.CharField(choices=[('main', 'Main'), ('recto', 'Recto'), ('verso', 'Verso'), ('detail', 'detail'), ('signature', 'signature')], default='main', max_length=25),
        ),
        migrations.AlterField(
            model_name='image',
            name='checksum',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='license',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_first',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_last',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='service',
            field=models.CharField(choices=[('ask', 'Ask.fm'), ('facebook', 'Facebook'), ('flickr', 'Flickr'), ('foursquare', 'Foursquare'), ('github', 'GitHub'), ('googleplus', 'Google+'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('meetup', 'Meetup'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('snapchat', 'SnapChat'), ('tumblr', 'Tumblr'), ('twitter', 'Twitter'), ('vine', 'Vine'), ('whatsapp', 'WhatsApp'), ('yelp', 'Yelp'), ('youtube', 'YouTube')], max_length=25),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='value',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='work',
            name='version',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
