# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170930_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='active',
        ),
    ]
