# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_record_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('tag', 'tag'), ('category', 'category'), ('identifier', 'identifier')], max_length=25)),
                ('value', models.SlugField(unique=True)),
                ('vocabulary', models.CharField(blank=True, choices=[('visualist', 'The Visualist'), ('aat', 'Getty Art and Architecture Thesaurus'), ('ulan', 'Getty Union List of Artist Names'), ('lccn', 'Library of Congress Control Number'), ('viaf', 'Virtual International Authority File')], max_length=25, null=True)),
                ('description', models.TextField()),
                ('canonical_url', models.URLField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.Term')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='record',
        ),
        migrations.RemoveField(
            model_name='license',
            name='description',
        ),
        migrations.RemoveField(
            model_name='license',
            name='url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tags',
        ),
        migrations.AddField(
            model_name='license',
            name='canonical_url',
            field=models.URLField(default='example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='record',
            name='terms',
            field=models.ManyToManyField(blank=True, to='api.Term'),
        ),
    ]
