# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170912_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['value'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_start', '-date_end', 'name']},
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['value'], 'verbose_name_plural': 'nationalities'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name', '-created']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name_last', 'name_first', '-created'], 'verbose_name_plural': 'people'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name', '-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name', '-created']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['value']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['name', '-created']},
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('address_street', 'address_locality', 'address_region')]),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('value', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together=set([('phone_for', 'country', 'area', 'exchange', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([('service', 'value')]),
        ),
    ]
