# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171005_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='author_primary',
        ),
        migrations.AlterField(
            model_name='source',
            name='date',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='source',
            name='pages',
            field=models.CharField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='place',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='source',
            name='publisher',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, default='', max_length=250),
            preserve_default=False,
        ),
    ]
