# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171005_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
