# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170912_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='license',
        ),
        migrations.RemoveField(
            model_name='category',
            name='license',
        ),
        migrations.RemoveField(
            model_name='email',
            name='license',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='license',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='license',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='license',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='license',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='license',
        ),
    ]
