# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20171005_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='pages',
        ),
    ]
