# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170912_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='identifiers',
        ),
        migrations.AddField(
            model_name='identifier',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Record'),
            preserve_default=False,
        ),
    ]
