# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170930_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
