# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170930_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='same_as',
            field=models.ManyToManyField(blank=True, null=True, related_name='_term_same_as_+', to='api.Term'),
        ),
    ]
