# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_source_pages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='regions',
            new_name='region',
        ),
    ]
