# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_term_same_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='label',
        ),
    ]
