# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:19
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20171006_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='extra',
            new_name='properties',
        ),
        migrations.AddField(
            model_name='recordsource',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='recordsource',
            name='accessed',
            field=models.DateField(default=datetime.datetime(2017, 10, 6, 3, 19, 4, 878998, tzinfo=utc)),
        ),
    ]
