# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170912_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='source',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='source',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='source',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='source',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='source',
        ),
    ]
