# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_term_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='same_as',
            field=models.ManyToManyField(blank=True, related_name='_term_same_as_+', to='api.Term'),
        ),
    ]
