# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20171006_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordsource',
            name='accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
