# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170930_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='value',
            new_name='slug',
        ),
    ]
