# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171006_0335'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTimespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('born', 'born'), ('died', 'died'), ('started', 'started'), ('ended', 'ended'), ('lived', 'lived'), ('performed', 'performed'), ('occurred', 'occurred'), ('created', 'created')], max_length=25)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recorddate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recorddate',
            name='record',
        ),
        migrations.RemoveField(
            model_name='recordlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recordlocation',
            name='record',
        ),
        migrations.AlterField(
            model_name='record',
            name='dates',
            field=models.ManyToManyField(through='api.RecordTimespace', to='api.Date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='locations',
            field=models.ManyToManyField(through='api.RecordTimespace', to='api.Location'),
        ),
        migrations.DeleteModel(
            name='RecordDate',
        ),
        migrations.DeleteModel(
            name='RecordLocation',
        ),
        migrations.AddField(
            model_name='recordtimespace',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Record'),
        ),
    ]
