# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20171001_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='value',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
