# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_term_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='dates',
        ),
    ]
