# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20171006_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtimespace',
            name='duration_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
