# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_recordtimespace_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtimespace',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Date'),
        ),
        migrations.AlterField(
            model_name='recordtimespace',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
