# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20171006_0401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='precision_days',
            new_name='precision_seconds',
        ),
        migrations.RenameField(
            model_name='recordtimespace',
            old_name='duration_days',
            new_name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=set([('date', 'precision_seconds')]),
        ),
    ]
