# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20171006_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtimespace',
            name='date',
        ),
        migrations.RemoveField(
            model_name='recordtimespace',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recordtimespace',
            name='record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='record',
            name='locations',
        ),
        migrations.AlterField(
            model_name='relation',
            name='dobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relation_direct_object', to='api.Record'),
        ),
        migrations.DeleteModel(
            name='RecordTimespace',
        ),
    ]
