# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20171006_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='sources',
            field=models.ManyToManyField(blank=True, to='api.Source'),
        ),
    ]
