# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 12:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20171006_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
    ]
