# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20171006_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='precision_seconds',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='date',
            name='precision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='relation',
            name='dates',
            field=models.ManyToManyField(blank=True, to='api.Date'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='locations',
            field=models.ManyToManyField(blank=True, to='api.Location'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='predicate',
            field=models.CharField(choices=[('has_beginning', 'has beginning/birth'), ('has_ending', 'has ending/death'), ('has_affiliation', 'has affiliation'), ('has_contributor', 'has contributor'), ('has_creator', 'has creator'), ('has_curator', 'has curator'), ('has_editor', 'has editor'), ('has_employee', 'has employee'), ('has_exhibitor', 'has exhibitor'), ('has_friend', 'has friend'), ('has_location', 'has location'), ('has_member', 'has member'), ('has_organizer', 'has organizer'), ('has_owner', 'has owner'), ('has_parent', 'has parent'), ('has_performer', 'has performer'), ('has_producer', 'has producer'), ('has_publisher', 'has publisher'), ('has_spouse', 'has spouse'), ('has_primary', 'is a subsidiary of'), ('has_translator', 'has translator'), ('has_venue', 'has venue'), ('part_of', 'part of'), ('same_as', 'same as')], max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=set([('date', 'duration', 'precision')]),
        ),
    ]
