# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20171006_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='predicate',
            field=models.CharField(choices=[('has_affiliation', 'affiliated with'), ('has_contributor', 'has contributor'), ('has_creator', 'has creator'), ('has_curator', 'has curator'), ('has_date', 'has date'), ('has_editor', 'has editor'), ('has_employee', 'has employee'), ('has_exhibitor', 'has exhibitor'), ('has_existence', 'exists'), ('has_friend', 'has friend'), ('has_life', 'is alive'), ('has_location', 'has location (NOT venue)'), ('has_member', 'has member'), ('has_organizer', 'has organizer'), ('has_owner', 'has owner'), ('has_parent', 'has parent'), ('has_performer', 'has performer'), ('has_primary', 'is a subsidiary of'), ('has_producer', 'has producer'), ('has_publisher', 'has publisher'), ('has_spouse', 'is married to'), ('has_translator', 'has translator'), ('has_venue', 'has venue'), ('part_of', 'part of'), ('same_as', 'same as')], max_length=25),
        ),
    ]
