# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20171006_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
    ]
