# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20171007_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='dobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_dobject', to='api.Record'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_by_subject', to='api.Record'),
        ),
    ]
