# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20171007_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='url',
            new_name='source_url',
        ),
    ]
