# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20171007_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='sublabels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=['test'], size=None),
            preserve_default=False,
        ),
    ]
