# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20171007_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='description',
            new_name='descriptions',
        ),
    ]
