# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 18:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_item_type', models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='PERSONAL', max_length=20)),
                ('service', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('PINTEREST', 'Pinterest'), ('TUMBLR', 'Tumblr'), ('TWITTER', 'Twitter')], default='FACEBOOK', max_length=20)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('contact_types', models.CharField(choices=[('PERSON', 'person'), ('ARCHIVE', 'archive'), ('ASSOCIATION', 'association'), ('COMPANY', 'company'), ('ENSEMBLE', 'ensemble'), ('FOUNDATION', 'foundation'), ('GALLERY', 'gallery'), ('LIBRARY', 'library'), ('MUSEUM', 'museum'), ('SCHOOL', 'school')], default='PERSON', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('org_members', models.ManyToManyField(related_name='member_of', to='directory.Contact')),
                ('related_contacts', models.ManyToManyField(blank=True, to='directory.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_item_type', models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='PERSONAL', max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_set', to='directory.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_item_type', models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='PERSONAL', max_length=20)),
                ('country_code', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)])),
                ('area_code', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999)])),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_set', to='directory.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_item_type', models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='PERSONAL', max_length=20)),
                ('url', models.URLField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_set', to='directory.Contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
