# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='parent_organizations', to='directory.Contact'),
        ),
    ]
