# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_types',
            field=models.CharField(choices=[('ARCHIVE', 'archive'), ('ASSOCIATION', 'association'), ('COMPANY', 'company'), ('CONSORTIUM', 'consortium'), ('FOUNDATION', 'foundation'), ('GALLERY', 'gallery'), ('LIBRARY', 'library'), ('MUSEUM', 'museum'), ('SCHOOL', 'school')], default='ASSOCIATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], max_length=20),
        ),
    ]
