# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170118_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contacts',
            new_name='contact_parents',
        ),
    ]
