# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20170114_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='service',
            field=models.CharField(choices=[('FACEBOOK', 'Facebook'), ('PINTEREST', 'Pinterest'), ('TUMBLR', 'Tumblr'), ('TWITTER', 'Twitter')], default='FACEBOOK', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='BUSINESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='BUSINESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='BUSINESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='phone',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='BUSINESS', max_length=20),
        ),
        migrations.AlterField(
            model_name='website',
            name='contact_item_type',
            field=models.CharField(choices=[('BUSINESS', 'business'), ('PERSONAL', 'personal')], default='BUSINESS', max_length=20),
        ),
    ]
