# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20170118_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('MEMBER', 'is member of'), ('FRIEND', 'is friend of')], default='MEMBER', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactselfjoin',
            name='child',
        ),
        migrations.RemoveField(
            model_name='contactselfjoin',
            name='parent',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_parents',
            field=models.ManyToManyField(blank=True, through='directory.Relationship', to='directory.Contact'),
        ),
        migrations.DeleteModel(
            name='ContactSelfJoin',
        ),
        migrations.AddField(
            model_name='relationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parents', to='directory.Contact'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='directory.Contact'),
        ),
    ]
