# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20170118_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='directory.Contact'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='directory.Contact'),
        ),
    ]
