# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Record')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('name', models.CharField(max_length=100)),
                ('synopsis', models.TextField(blank=True, max_length=250, null=True)),
                ('event_type', models.CharField(choices=[('EXHIBITION', 'exhibition'), ('PERFORMANCE', 'performance')], default='EXHIBITION', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.record',),
        ),
    ]
