# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='related_events',
            field=models.ManyToManyField(related_name='_event_related_events_+', to='calendar.Event'),
        ),
    ]
