# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
        ('calendar', '0002_event_related_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venues',
            field=models.ManyToManyField(to='atlas.Venue'),
        ),
    ]
