# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.Record')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.record',),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('place_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Place')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.place',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.space',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.space',),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.space',),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.space',),
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('space_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tour.Space')),
            ],
            options={
                'abstract': False,
            },
            bases=('tour.space',),
        ),
    ]
