BaseSchema: &Base
    slug:
        type: string
        regex: '^[a-z0-9-]+$'
        unique: true

RecordSchema: &Record
    <<: *Base
    featured:
        type: boolean
        default: false
    approved:
        type: boolean
        default: false
    web_public:
        type: boolean
        default: true
    # same_as:
    # categories:

PersonSchema:
    <<: *Record
    last_name:
        type: string
        minlength: 1
        required: true
        # unique': false
    first_name:
        type: string
        minlength: 1
        required: false
        # unique: false
