# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placefinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVenueJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('OCCUPIED', 'occupant of'), ('OWNER', 'owner of')], default='OCCUPIED', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EventContactJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('ORGANIZED', 'organized by')], default='ORGANIZED', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EventVenueJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('HOSTED', 'hosted by')], default='SHOWN', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkContactJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('CREATED', 'created by'), ('PUBLISHED', 'published by'), ('OWNED', 'owned by')], default='CREATED', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEventJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('SHOWN', 'shown during')], default='SHOWN', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='WorkVenueJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('SHOWN', 'shown at')], default='SHOWN', max_length=25)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placefinder.Venue')),
            ],
        ),
    ]
