# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='records',
        ),
        migrations.RemoveField(
            model_name='identifier',
            name='records',
        ),
        migrations.RemoveField(
            model_name='name',
            name='records',
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
