# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('timeline', '0001_initial'),
        ('base', '0001_initial'),
        ('catalog', '0001_initial'),
        ('placefinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workvenuejoin',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Work'),
        ),
        migrations.AddField(
            model_name='workeventjoin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Event'),
        ),
        migrations.AddField(
            model_name='workeventjoin',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Work'),
        ),
        migrations.AddField(
            model_name='workcontactjoin',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Contact'),
        ),
        migrations.AddField(
            model_name='workcontactjoin',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Work'),
        ),
        migrations.AddField(
            model_name='eventvenuejoin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Event'),
        ),
        migrations.AddField(
            model_name='eventvenuejoin',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placefinder.Venue'),
        ),
        migrations.AddField(
            model_name='eventcontactjoin',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Contact'),
        ),
        migrations.AddField(
            model_name='eventcontactjoin',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.Event'),
        ),
        migrations.AddField(
            model_name='contactvenuejoin',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.Contact'),
        ),
        migrations.AddField(
            model_name='contactvenuejoin',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placefinder.Venue'),
        ),
    ]
