# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170115_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RightSet',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterField(
            model_name='record',
            name='sources',
            field=models.ManyToManyField(to='aggregator.Source'),
        ),
    ]
