# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('timeline', '0001_initial'),
        ('base', '0001_initial'),
        ('placefinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('length', models.DecimalField(decimal_places=3, max_digits=7)),
                ('width', models.DecimalField(decimal_places=3, max_digits=7)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('dimension_unit', models.CharField(choices=[('mm', 'millimeters'), ('cm', 'centimeters'), ('m', 'meters'), ('in', 'inches'), ('ft', 'feet')], default='in', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('contacts', models.ManyToManyField(blank=True, through='base.WorkContactJoin', to='directory.Contact')),
                ('dimension_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.DimensionSet')),
                ('events', models.ManyToManyField(blank=True, through='base.WorkEventJoin', to='timeline.Event')),
                ('venues', models.ManyToManyField(blank=True, through='base.WorkVenueJoin', to='placefinder.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
