# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0003_auto_20170115_2022'),
        ('catalog', '0002_work_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='atlas.Venue'),
            preserve_default=False,
        ),
    ]
