from django.contrib import admin
from api.models import (
    Address,
    Category,
    Collection,
    Email,
    Event,
    Identifier,
    Image,
    License,
    Nationality,
    Organization,
    Page,
    Person,
    Phone,
    Place,
    Post,
    Resource,
    Snippet,
    SocialAccount,
    Tag,
    Work,
)

admin.site.register(Address)
admin.site.register(Category)
admin.site.register(Collection)
admin.site.register(Email)
admin.site.register(Event)
admin.site.register(Identifier)
admin.site.register(Image)
admin.site.register(License)
admin.site.register(Nationality)
admin.site.register(Organization)
admin.site.register(Page)
admin.site.register(Person)
admin.site.register(Phone)
admin.site.register(Place)
admin.site.register(Post)
admin.site.register(Resource)
admin.site.register(Snippet)
admin.site.register(SocialAccount)
admin.site.register(Tag)
admin.site.register(Work)
